export const HOME = 'HomeScreen';
export const BOTTOM_TABS = 'BottomTabs';
export const EXPLORE_BRAND = 'ExploreBrand';
export const NOTIFICATION = 'Notification';
export const INTRODUCTION = 'Introduction';
export const PROFILE = 'PROFILE';


///

export const NBHLOGIN = 'NBHLOGIN';
export const NBHOTP = 'NBHOTP';
export const NBHFORGETPASSWORD = 'NBHFORGETPASSWORD';
export const NBHCREATENEWPASSWOERD = 'NBHCREATENEWPASSWOERD';
export const NBHSIGNUP_SCREEN = 'NBHSIGNUP_SCREEN';
export const EDITPROFILE_SCREEN = 'EDITPROFILE_SCREEN';
export const MAKEPAYMENT_SCREEN = 'MAKEPAYMENT_SCREEN';
export const MAKEPAYMENTEVENTS_SCREEN = 'MAKEPAYMENTEVENTS_SCREEN';
export const MAKEPAYMENTADVERTISMENTPOST_SCREEN = 'MAKEPAYMENTADVERTISMENTPOST_SCREEN';







export const HOME_SCREEN = 'HOME_SCREEN';
export const NBHMEMBER_SCREEN = 'NBHMEMBER_SCREEN';
export const SEARCHBYTAG_SCREEN = 'SEARCHBYTAG_SCREEN';
export const NBHMEMBERDETAIL_SCREEN = 'NBHMEMBERDETAIL_SCREEN';
export const NBHBUSSNESSDETAIL_SCREEN = 'NBHBUSSNESSDETAIL_SCREEN';
export const MYFOLLOWING_SCREEN = 'MYFOLLOWING_SCREEN';
export const POSTIMAGE_SCREEN = 'POSTIMAGE_SCREEN';
export const MYTIMELINE_SCREEN = 'MYTIMELINE_SCREEN';
export const ADDPOST_SCREEN = 'ADDPOST_SCREEN';
export const FREESHOPS_SCREEN = 'FREESHOPS_SCREEN';
export const SELECTVARIANT_SCREEN = 'SELECTVARIANT_SCREEN';
export const ORDERDETAILS_SCREEN = 'ORDERDETAILS_SCREEN';
export const ORDERLISTING_SCREEN = 'ORDERLISTING_SCREEN';
export const COMMENTS_SCREEN = 'COMMENTS_SCREEN';
export const TIMELINE_SCREEN = 'TIMELINE_SCREEN';
export const CATALOGUEDETAIL_SCREEN = 'CATALOGUEDETAIL_SCREEN';
export const ADDCATALOGUE_SCREEN = 'ADDCATALOGUE_SCREEN';
export const ADDCLIENTS_SCREEN = 'ADDCLIENTS_SCREEN';
export const MYASKLIST_SCREEEN = 'MYASKLIST_SCREEEN';
export const PRODUCTCATALOGUE_SCREEN = 'PRODUCTCATALOGUE_SCREEN';
export const MYACCOUNT_SCREEN = 'MYACCOUNT_SCREEN';
export const MYPROFILE_SCREEN = 'MYPROFILE_SCREEN';
export const MYCLIENT_SCREEN = 'MYCLIENT_SCREEN';
export const POSTADVERTISE_SCREEN = 'POSTADVERTISE_SCREEN';
export const CIRCULARS_SCREEN = 'CIRCULARS_SCREEN';
export const EVENTS_SCREEN = 'EVENTS_SCREEN';
export const UTILITYDESK_SCREEN = 'UTILITYDESK_SCREEN';
export const SCHEDULEMEETUP_SCREEN = 'SCHEDULEMEETUP_SCREEN';
export const SEASONALGREETINGS_SCREEN = 'SEASONALGREETINGS_SCREEN';
export const GREETINGS_DETAILS_SCREEN = 'GREETINGS_DETAILS_SCREEN';
export const UPLOADACHIVEMETN_SCREEN = 'UPLOADACHIVEMETN_SCREEN';
export const ADVETISEPRODUCT_SCREEN = 'ADVETISEPRODUCT_SCREEN';
export const VIEWPRODUCT_SCREEN = 'VIEWPRODUCT_SCREEN';
export const POSTADDETAIL_SCREEN = 'POSTADDETAIL_SCREEN';
export const WALLET_SCREEN = 'WALLET_SCREEN';
export const ADD_ADDRESS_MAP_SCREEN = 'ADD_ADDRESS_MAP_SCREEN';
export const ADD_ADDRESS_SCREEN = 'ADD_ADDRESS_SCREEN';
export const GEO_LOCATION_SCREEN = 'GEO_LOCATION_SCREEN';

export const CHAT_SCREEN = 'CHAT_SCREEN';

export const CHATIMAGE_SCREEN = 'CHATIMAGE_SCREEN';
export const DOCUMENT_VIEW_SCREEN = 'DOCUMENT_VIEW_SCREEN';


export const SEND_BOX = 'SEND_BOX';

export const ADDRESS_LIST_SCREEN = 'ADDRESS_LIST_SCREEN';

export const BACKIMAGE = 'BACKIMAGE';
export const DEEPLINK_POST = 'DEEPLINK_POST';


export const INVOICE = 'INVOICE';




// InVoiceScreen


































